### PR TITLE
Complete GKE testing

### PR DESCRIPTION
**Pull request by sonnysideup**
### Environment

- rabbitmq
- docker registry (secure & insecure)
- redis
- istio
- hephaestus (using pr images)

### Tests

- [x] all webhook validations
- [x] push to registry w/o auth
- [x] push to registry w/ auth using inline credentials
- [x] push to registry w/ auth using secret credentials
- [x] push to registry w/ auth failure
- [x] push to GAR using cloud-provided credentials
- [x] build image using build-args
- [x] build failure with bad Dockerfile
- [x] concurrent builds
- [x] multi-stage builds
- [x] ensure JSON log delivery to redis sink
- [x] ensure rabbitmq message delivery

### CODE REVIEW

**Comment by sonnysideup** [comment]
@steved Check this out if/when you get a chance. I think I've covered all of the major test cases but perhaps I missed a few. Thanks.

**Review by steved — COMMENTED** [review]
LGTM, no major comments. Rootless isn't covered, but I'm not sure if you want to in this PR or down the line.

**Pull request merged**
