### PR TITLE
update functional tests and associated resources

### PR DESCRIPTION
**Pull request by steved**
Gets the functional tests working again.

### CODE REVIEW

**Review by fraenkel — COMMENTED** [review]
I dont see any "Functional" actions passing.

**Comment by steved** [comment]
They're comment based, so I need to merge this into main first. It was tested here: https://github.com/dominodatalab/hephaestus/pull/155.

**Comment by fraenkel** [comment]
all the runs have failed.

**Review by fraenkel — APPROVED** [review]
I am assuming some future PR will get it green

**Pull request merged**
